In [1]:
from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
BASE_DIR = Path.cwd()
DATA_DIR = BASE_DIR / "data"

sales = pd.read_csv(DATA_DIR / "sales_train.csv")
test = pd.read_csv(DATA_DIR / "test.csv")
items = pd.read_csv(DATA_DIR / "items.csv")
shops = pd.read_csv(DATA_DIR / "shops.csv")
categories = pd.read_csv(DATA_DIR / "item_categories.csv")

print(sales.shape)
sales.head()

(2935849, 6)

         date  date_block_num  shop_id  item_id  item_price  item_cnt_day
0  02.01.2013               0       59    22154      999.00           1.0
1  03.01.2013               0       25     2552      899.00           1.0
2  05.01.2013               0       25     2552      899.00          -1.0
3  06.01.2013               0       25     2554     1709.05           1.0
4  15.01.2013               0       25     2555     1099.00           1.0

In [3]:
sales[sales.duplicated(keep=False)].sort_values(
    ["date", "shop_id", "item_id"]
)

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day
1671872,01.05.2014,16,50,3423,999.0,1.0
1671873,01.05.2014,16,50,3423,999.0,1.0
76961,05.01.2013,0,54,20130,149.0,1.0
76962,05.01.2013,0,54,20130,149.0,1.0
1866322,12.07.2014,18,25,3423,999.0,1.0
1866340,12.07.2014,18,25,3423,999.0,1.0
1435365,23.02.2014,13,50,3423,999.0,1.0
1435367,23.02.2014,13,50,3423,999.0,1.0
1496765,23.03.2014,14,21,3423,999.0,1.0
1496766,23.03.2014,14,21,3423,999.0,1.0
2198564,31.12.2014,23,42,21619,499.0,1.0
2198566,31.12.2014,23,42,21619,499.0,1.0

In [4]:
sales_clean = sales.drop_duplicates().copy()

In [6]:
sales_clean.duplicated().sum()

np.int64(0)

In [7]:
sales_clean["item_price"].describe()

count    2.935843e+06
mean     8.908535e+02
std      1.729801e+03
min     -1.000000e+00
25%      2.490000e+02
50%      3.990000e+02
75%      9.990000e+02
max      3.079800e+05
Name: item_price, dtype: float64

In [8]:
sales_clean[sales_clean["item_price"] <=0]

              date  date_block_num  shop_id  item_id  item_price  item_cnt_day
484683  15.05.2013               4       32     2973        -1.0           1.0

In [9]:
sales_clean = sales_clean[sales_clean["item_price"] > 0].copy()

In [10]:
(sales_clean["item_price"] <= 0).sum()

np.int64(0)

In [11]:
sales_clean["item_cnt_day"].describe()

count    2.935842e+06
mean     1.242641e+00
std      2.618838e+00
min     -2.200000e+01
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      2.169000e+03
Name: item_cnt_day, dtype: float64

In [12]:
sales_clean.nsmallest(10, "item_cnt_day")

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day
1057907,02.11.2013,10,12,8023,15.000000,-22.0
1835454,10.07.2014,18,14,20949,5.000000,-16.0
2048519,10.10.2014,21,12,9242,1433.333333,-9.0
59156,18.01.2013,0,12,1590,2599.000000,-6.0
940092,19.10.2013,9,42,3732,2599.000000,-6.0
59155,10.01.2013,0,12,1590,2599.000000,-5.0
93576,21.01.2013,0,43,20384,1599.000000,-5.0
2458733,18.02.2015,25,2,16790,2899.000000,-5.0
2619997,29.05.2015,28,6,4894,3999.000000,-5.0
222426,22.02.2013,1,28,21323,199.000000,-4.0

In [13]:
sales_clean.nlargest(10, "item_cnt_day")

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day
2909818,28.10.2015,33,12,11373,0.908714,2169.0
2326930,15.01.2015,24,12,20949,4.000000,1000.0
2864235,30.09.2015,32,12,9248,1692.526158,669.0
2851091,30.09.2015,32,55,9249,1702.825746,637.0
2608040,14.04.2015,27,12,3731,1904.548077,624.0
2626181,19.05.2015,28,12,11373,155.192950,539.0
2851073,29.09.2015,32,55,9249,1500.000000,533.0
2048518,02.10.2014,21,12,9242,1500.000000,512.0
2067669,09.10.2014,21,55,19437,899.000000,508.0
2864260,29.09.2015,32,12,9248,1500.000000,504.0

In [14]:
sales_clean.nlargest(20, "item_cnt_day")

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day
2909818,28.10.2015,33,12,11373,0.908714,2169.0
2326930,15.01.2015,24,12,20949,4.000000,1000.0
2864235,30.09.2015,32,12,9248,1692.526158,669.0
2851091,30.09.2015,32,55,9249,1702.825746,637.0
2608040,14.04.2015,27,12,3731,1904.548077,624.0
2626181,19.05.2015,28,12,11373,155.192950,539.0
2851073,29.09.2015,32,55,9249,1500.000000,533.0
2048518,02.10.2014,21,12,9242,1500.000000,512.0
2067669,09.10.2014,21,55,19437,899.000000,508.0
2864260,29.09.2015,32,12,9248,1500.000000,504.0
1573253,22.04.2014,15,27,8057,1200.000000,502.0
1708207,28.06.2014,17,25,20949,5.000000,501.0
2257299,19.12.2014,23,12,20949,4.000000,500.0
2909401,14.10.2015,33,12,20949,4.000000,500.0
2625847,19.05.2015,28,12,10209,1499.000000,480.0
2067677,09.10.2014,21,55,19445,1249.000000,412.0
1501160,15.03.2014,14,24,20949,5.000000,405.0
1573252,23.04.2014,15,27,8057,1200.000000,401.0
2067667,04.10.2014,21,55,19437,899.000000,401.0
2626133,19.05.2015,28,12,11370,171.661808,343.0

In [15]:
sales_clean[sales_clean["item_cnt_day"] == sales_clean["item_cnt_day"].max()]

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day
2909818,28.10.2015,33,12,11373,0.908714,2169.0

In [16]:
max_row = sales_clean.loc[
    sales_clean["item_cnt_day"].idxmax()
]

In [17]:
max_row = sales_clean.loc[
    sales_clean["item_cnt_day"].idxmax()
]

sales_clean[
    (sales_clean["shop_id"] == max_row["shop_id"])&
    (sales_clean["item_id"] == max_row["item_id"])
].sort_values("date")

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day
176790,01.02.2013,1,12,11373,229.000000,1.0
1547381,01.03.2014,14,12,11373,119.181818,22.0
2608327,01.04.2015,27,12,11373,383.333333,3.0
2698598,01.06.2015,29,12,11373,139.583333,12.0
2731629,01.07.2015,30,12,11373,305.000000,6.0
...,...,...,...,...,...,...
1547394,31.03.2014,14,12,11373,114.483871,31.0
2531931,31.03.2015,26,12,11373,306.500000,2.0
1830096,31.07.2014,18,12,11373,236.000000,3.0
2805531,31.08.2015,31,12,11373,529.142857,7.0
2257993,31.12.2014,23,12,11373,38.500000,4.0

In [19]:
sales_clean.nlargest(5, "item_cnt_day")

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day
2909818,28.10.2015,33,12,11373,0.908714,2169.0
2326930,15.01.2015,24,12,20949,4.000000,1000.0
2864235,30.09.2015,32,12,9248,1692.526158,669.0
2851091,30.09.2015,32,55,9249,1702.825746,637.0
2608040,14.04.2015,27,12,3731,1904.548077,624.0

In [20]:
sales_clean[sales_clean["item_cnt_day"] >= 1000]

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day
2326930,15.01.2015,24,12,20949,4.000000,1000.0
2909818,28.10.2015,33,12,11373,0.908714,2169.0

In [21]:
(sales_clean["item_cnt_day"] >= 1000).sum()

np.int64(2)

In [22]:
sales_clean = sales_clean[
    sales_clean["item_cnt_day"] < 1000
].copy()

In [23]:
sales_clean["item_cnt_day"].max()

np.float64(669.0)

In [24]:
(sales_clean["item_price"] <= 0).sum()

np.int64(0)

In [25]:
sales_clean[
    sales_clean["item_price"] <= 0
]

Empty DataFrame
Columns: [date, date_block_num, shop_id, item_id, item_price, item_cnt_day]
Index: []

In [26]:
sales_clean["item_price"].min()

np.float64(0.07)

In [27]:
sales_clean.nlargest(10, "item_price")

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day
1163158,13.12.2013,11,12,6066,307980.0,1.0
885138,17.09.2013,8,12,11365,59200.0,1.0
1488135,20.03.2014,14,25,13199,50999.0,1.0
2327159,29.01.2015,24,12,7241,49782.0,1.0
2885692,23.10.2015,33,42,13403,42990.0,1.0
2910156,29.10.2015,33,12,13403,42990.0,1.0
2917760,20.10.2015,33,3,13403,42990.0,1.0
2931380,20.10.2015,33,22,13403,42990.0,1.0
1006638,24.10.2013,9,12,7238,42000.0,1.0
2893100,20.10.2015,33,38,13403,41990.0,1.0

In [28]:
(sales_clean["item_price"] >= 100000).sum()

np.int64(1)

In [29]:
sales_clean[
    sales_clean["item_price"] >= 100000
]

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day
1163158,13.12.2013,11,12,6066,307980.0,1.0

In [30]:
expensive_row = sales_clean.loc[
    sales_clean["item_price"].idxmax()
]

sales_clean[
    sales_clean["item_id"] == expensive_row["item_id"]
].sort_values("date")

,date,date_block_num,shop_id,item_id,item_price,item_cnt_day
1163158,13.12.2013,11,12,6066,307980.0,1.0

In [31]:
sales_clean = sales_clean[
    sales_clean["item_price"] < 100000
].copy()

In [32]:
sales_clean["item_price"].max()

np.float64(59200.0)

In [35]:
monthly_sales = (
    sales_clean.groupby(
    ["date_block_num", "shop_id", "item_id"],
    as_index=False
    )["item_cnt_day"]
    .sum()
    .rename(
        columns={"item_cnt_day": "item_cnt_month"}
    )
)
monthly_sales["item_cnt_month"] = (
    monthly_sales["item_cnt_month"]
    .clip(0,20)
)
monthly_sales.head()

   date_block_num  shop_id  item_id  item_cnt_month
0               0        0       32             6.0
1               0        0       33             3.0
2               0        0       35             1.0
3               0        0       43             1.0
4               0        0       51             2.0